<div class="container">
    <h1>Specifikacja</h1>
    <ul>
        <li>HTML5</li>
        <li>Zend framework 1</li>
        <li>CSS framework - Bootstrap http://getbootstrap.com/</li>
    </ul>
    <h1>Opis projektu</h1>
    Projekt jest sklepem internetowy sprzedającym buty. Baza produktów jest zaczerpnięta ze sklepu zebra-buty.pl i zawiera 100 produktów.
    <br/><br/>
    W projekcie użyto następujacych technologii:
    <ul>
        <li>Ajax - użyty w celu dodawania produktów do koszyka.</li>
        <li>Baza Mysql - jako magazyn danych</li>
        <li>Koszyk jest przetrzymywany w sesji.</li>
        <li>Klient ma dostęp do listy zamówień zrealizowanych w danej sesji.</li>
        <li>Xml - baza produktów została zaimportowana z następujaćego pliku: http://zebra-buty.pl/xml/ceneo.php?limit=100</li>
    </ul>
    <br/><br/>
    Klient w menu górnym (nawigacyjnym) ma dostęp do oferty sklepu - może filtrować asortyment po typie glównym - damskie, męskie, akcesoria. Lub po rodzaju obuwia np: trzewiki czy szpili. Na też bezpośredni dostęp do koszyka oraz listy swoich zamowień.
    <br/></br>
    <img src="/img/about/show-basket.png" alt="koszyk podgląd" />
    <br/></br>
    <img src="/img/about/show-order.png" alt="zamówienia podgląd" />
    <br/></br>
    Dzięki zastosowaniu Ajaxa użytkownik po naciśnieciu przycisku do koszyka, dostaje czytelny komunikat o wyniku operacji:
    <br/></br>
    <img src="/img/about/basket.png" alt="koszyk" />
    <br/></br>
    Strona jest dostosowana pod urządzenia mobilne.
    <br/></br>
    <img src="/img/about/mobile.png" alt="urzadzenia mobilne" />
</div>