<div class="container">
    <h1>Specifikacja</h1>
    <ul>
        <li>HTML5</li>
        <li>Zend framework 1</li>
        <li>Bootstrap http://getbootstrap.com/</li>
    </ul>
    <h1>Opis projektu</h1>
    Projekt jest sklepem internetowy sprzedajacym buty. Baza produktów jest zaczerpnieta ze sklepu zebra-buty.pl i zawiera 100 produktów.
    <br/><br/>
    W projekcie użyto nastepujacych technoli:
    <ul>
        <li>Ajax - użyty w celu dodawania produktów do koszyka.</li>
        <li>Baza Mysql - jako magazyn danych</li>
        <li>Koszyk jest przetrzymywany w sesji.</li>
        <li>Klient ma dostęp do listy zamówień zrealizowanych w danej sesji.</li>
    </ul>
    <br/><br/>
    Klient w menu nawigacyjnym górny ma dostep do oferty sklepu - moze filtrowac asortyment po typie glównym - damskie, męskie, akcesoria. Lub po rodzaju obuwia np: trzewiki czy szpili. Na też bezpośredni dostęp do koszyka o raz listy swoich zamowień.
    <br/></br>
    Strona jest dostosowana pod użądzenia mobilne.
</div>