<?php if ($this->pageCount & $this->pageCount > 1): ?>
    <div class="row">
    <nav>
        <ul class="pagination">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
                <li>
                    <a href="<?php echo $this->url(array('page' => $this->previous)); ?>" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a> 
                </li>
            <?php else: ?>
                <li>
                    <span aria-hidden="true">&laquo;</span>
                </li>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $this->url(array('page' => $page)); ?>">
                            <?php echo $page; ?>
                        </a> 
                    </li>
                <?php else: ?>
                    <li class="active"><span><?php echo $page; ?></span></li>
                <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
                <li>
                    <a href="<?php echo $this->url(array('page' => $this->next)); ?>" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            <?php else: ?>
                <li>
                    <span aria-hidden="true">&raquo;</span>
                </li>
            <?php endif; ?>
        </ul>
    </nav>
    </div>
<?php endif; ?>
